---
- hosts: all
  gather_facts: no
  become: yes
  become_user: root

  tasks:
    - name: Set database update script
      set_fact:
        update_sql: |
          DROP VIEW  IF EXISTS vw_reserves;
          DROP PROCEDURE IF EXISTS sp_reserve_player_update(res_id uuid, per_id uuid, c integer);
          ALTER TABLE reserve_players ADD COLUMN IF NOT EXISTS arrive_time TIMESTAMP DEFAULT '0001-01-01';

    - name: Copy binary to temp directory
      copy:
        src: "{{ bot_name }}"
        dest: "{{ src_path }}/{{ bot_name }}"
      notify:
        - restart_service
        - update_binary

    - name: Create service file
      copy:
        dest: /etc/systemd/system/{{ bot_name }}.service
        content: |
          [Unit]
          Description=Volley bot
          After=network.target
          Wants=postgresql.service
          [Service]
          EnvironmentFile=/etc/vbot/{{ bot_name }}.env
          ExecStart=/usr/sbin/vbot/{{ bot_name }}
      notify:
        - restart_service

    - name: Create service envinronment file
      copy:
        dest: /etc/vbot/{{ bot_name }}.env
        mode: "0644"
        content: |
          PGURL={{ pg_url }}
          TOKEN={{ token }}
          LOCATION={{ location }}
      notify:
        - restart_service

  handlers:
    - name: Stop bot service
      ansible.builtin.systemd:
        name: "{{ bot_name }}"
        state: stopped
      listen: restart_service
    
    - name: Update database
      when:
        update_sql | length > 0 
      shell: | 
        psql {{ pg_url }} -c "{{ update_sql }}"
      become: true
      become_user: postgres
      listen: update_binary

    - name: Update bot binary
      copy:
        src: "{{ src_path }}/{{ bot_name }}"
        dest: "/usr/sbin/vbot/{{ bot_name }}"
        remote_src: true
        mode: "0700" 
      listen: update_binary

    - name: Change bot service to requested state
      ansible.builtin.systemd:
        name: "{{ bot_name }}"
        state: "{{ bot_state | d('started') }}"
      listen: restart_service
...
