name: Foxvolley

on:
  push:
    branches: [ master ]

env:
  BOT_NAME: foxbot

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Test
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: ['test']
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - uses: ./.github/build
      with: 
        bot_name: ${{ env.BOT_NAME }}

  deploy:
    runs-on: ubuntu-latest
    environment: foxvolley
    needs: ['build']
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: vbot-bin
        path: ./.github/ansible

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
        directory: ./.github/ansible
        key: ${{ secrets.SSH_KEY }}
        inventory: |
          [all:vars]
          src_path=${{ secrets.DELIVER_PATH }}
          pg_url=${{ secrets.PG_URL }}
          token=${{ secrets.TOKEN }}
          location=${{ secrets.LOCATION }}

          [all]
          ${{ secrets.HOST }} ansible_user=${{ secrets.DEPLOY_USER }}
        options: --extra-vars bot_name=${{ env.BOT_NAME}}
...
