name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go build -v ./...
        ls

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy bot 
      uses: actions/setup-go@v2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH2 }}
        port: ${{ secrets.PORT }}
        source: "*/*"
        target: "/root/"
