name: Testing

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...
